type: Add retry to Exec resource
Cinder type needs to be created after Cinder API service start.
There is a race condition where the Exec can be run during Cinder API is
still trying to start.

If it's the case, the Exec will fail like this:
ERROR: Unable to establish connection to http://127.0.0.1:8776

This patch aims to retry another time after waiting 5 seconds, which is
a fair amount of time to wait for Cinder-API service.

Change-Id: I1c5caa00d87178d669d66736404e38214eed1ab6